models/Comment.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "comment".
 *
 * @property integer $id
 * @property string $texto
 * @property integer $usuario_id
 * @property integer $articulo_id
 * @property integer $estado
 *
 * @property Articulos $articulo
 * @property Usuarios $usuario
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */

    const STATUS_ALLOW = 1;
    const STATUS_DISALLOW = 0;

    public static function tableName()
    {
        return 'comentarios';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['usuario_id', 'articulo_id', 'estado'], 'integer'],
            [['texto'], 'string', 'max' => 255],
            [['articulo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Article::className(), 'targetAttribute' => ['articulo_id' => 'id']],
            [['usuario_id'], 'exist', 'skipOnError' => true, 'targetClass' => Usuarios::className(), 'targetAttribute' => ['usuario_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'texto' => 'Text',
            'usuario_id' => 'ID Usuario',
            'articulo_id' => 'Id Articulo',
            'estado' => 'Estado',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(Article::className(), ['id' => 'articulo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Usuarios::className(), ['id' => 'usuario_id']);
    }

    public function getDate()
    {
        return Yii::$app->formatter->asDate($this->fecha);
    }
    
    public function isAllowed()
    {
        return $this->estado;
    }

    public function allow()
    {
        $this->estado = self::STATUS_ALLOW;
        return $this->save(false);
    }

    public function disallow()
    {
        $this->estado = self::STATUS_DISALLOW;
        return $this->save(false);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Article;
use app\models\Category;
use app\models\CommentForm;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /* iNICIO */
    public function actionIndex()
    {
        $data = Article::getAll(5);
        $popular = Article::getPopular();
        $reciente = Article::getRecent();
        $categorias = Category::getAll();
        
        return $this->render('index',[
            'articles'=>$data['articles'],
            'paginacion'=>$data['paginacion'],
            'popular'=>$popular,
            'reciente'=>$reciente,
            'categorias'=>$categorias
        ]);
    }
    
    public function actionView($id)
    {
        $articulo = Article::findOne($id);
        $popular = Article::getPopular();
        $reciente = Article::getRecent();
        $categorias = Category::getAll();
        $comentarios = $articulo->getArticleComments();
        $comentariosForm = new CommentForm();

        $articulo->viewedCounter();
        
        return $this->render('single',[
            'articulo'=>$articulo,
            'popular'=>$popular,
            'reciente'=>$reciente,
            'categorias'=>$categorias,
            'comentarios'=>$comentarios,
            'comentariosForm'=>$comentariosForm
        ]);
    }
    
    public function actionCategory($id)
    {

        $data = Category::getArticlesByCategory($id);
        $popular = Article::getPopular();
        $reciente = Article::getRecent();
        $categorias = Category::getAll();
        
        return $this->render('category',[
            'articulos'=>$data['articulos'],
            'pagination'=>$data['pagination'],
            'popular'=>$popular,
            'reciente'=>$reciente,
            'categorias'=>$categorias
        ]);
    }

    public function actionComment($id)
    {
        $model = new CommentForm();
        
        if(Yii::$app->request->isPost)
        {
            $model->load(Yii::$app->request->post());
            if($model->saveComment($id))
            {
                Yii::$app->getSession()->setFlash('comment', 'Tu comentario se añadio correctamente!');
                return $this->redirect(['site/view','id'=>$id]);
            }
        }
    }

}

views/partials/comment.php
<?php if(!empty($comentarios)):?>

<?php foreach($comentarios as $comment):?>
    <div class="bottom-comment"><!--bottom comment-->
        <div class="comment-img">
            <img width="50" class="img-circle" src="" alt="">
        </div>

        <div class="comment-text">
            <a href="#" class="replay btn pull-right"> Subir</a>
            <h5> <?= $comment->user->nombre; ?> </h5>

            <p class="comment-date">
                <?= $comment->getDate();?>
            </p>


            <p class="para"><?= $comment->texto; ?></p>
        </div>
    </div>
<?php endforeach;?>

<?php endif;?>
<!-- end bottom comment-->

<?php if(!Yii::$app->user->isGuest):?>
<div class="leave-comment"><!--leave comment-->
    <h4>Deja tu respuesta:</h4>
    <?php if(Yii::$app->session->getFlash('comment')):?>
        <div class="alert alert-success" role="alert">
            <?= Yii::$app->session->getFlash('comment'); ?>
        </div>
    <?php endif;?>
    <?php $form = \yii\widgets\ActiveForm::begin([
        'action'=>['site/comment', 'id'=>$articulo->id],
        'options'=>['class'=>'form-horizontal contact-form', 'role'=>'form']])?>
    <div class="form-group">
        <div class="col-md-12">
            <?= $form->field($comentariosForm, 'comentario')->textarea(['class'=>'form-control','placeholder'=>'Escribe un mensaje'])->label(false)?>
        </div>
    </div>
    <button type="submit" class="btn send-btn">Enviar</button>
    <?php \yii\widgets\ActiveForm::end();?>
</div><!--end leave comment-->
<?php endif;?>

views/partials/sidebar.php
<?php
use yii\helpers\Url;
?>
<div class="col-md-2" data-sticky_column>
    <div class="primary-sidebar">

        <aside class="widget">
            <h6 class="widget-title text-center">Posts Populares</h6>
            <?php

            foreach($popular as $article):?>
                <div class="popular-post">
                    <a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>" class="popular-img"><img src="<?= $article->getImage();?>" alt="">

                        <div class="p-overlay"></div>
                    </a>

                    <div class="p-content">
                        <a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>" class="text-uppercase"><?= $article->titulo?></a>
                        <span class="p-date"><?= $article->getDate();?></span>

                    </div>
                </div>
            <?php endforeach;?>

        </aside>
        <aside class="widget pos-padding">
            <h6 class="widget-title text-center">Posts Recientes</h6>
            <?php foreach($reciente as $article):?>
                <div class="thumb-latest-posts">
                    <div class="media">
                        <div class="media-left">
                            <a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>" class="popular-img"><img src="<?= $article->getImage();?>" alt="">
                                <div class="p-overlay"></div>
                            </a>
                        </div>
                        <div class="p-content">
                            <a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>" class="text-uppercase"><?= $article->titulo?></a>
                            <span class="p-date"><?= $article->getDate();?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        </aside>
        <aside class="widget border pos-padding">
            <h3 class="widget-title text-uppercase text-center">Categorias</h3>
            <ul>
                <?php foreach($categorias as $category):?>
                    <li>
                        <a href="<?= Url::toRoute(['site/category','id'=>$category->id]);?>"><?= $category->titulo?></a>
                        <span class="post-count pull-right"> (<?= $category->getArticlesCount();?>)</span>
                    </li>
                <?php endforeach;?>

            </ul>
        </aside>
    </div>
</div>