models/Article.php
<?php

namespace app\models;

use Yii;
use yii\data\Pagination;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $titulo
 * @property string $descripcion
 * @property string $contenido
 * @property string $fecha
 * @property string $imagen
 * @property integer $vistas
 * @property integer $usuario_id
 * @property integer $estado
 * @property integer $categoria_id
 *
 * @property ArticleTag[] $articulosTag
 * @property Comments[] $comentarios
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'articulos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['titulo'], 'required'],
            [['titulo','descripcion','contenido'], 'string'],
            [['fecha'], 'date', 'format'=>'php:Y-d-m'],
            [['fecha'], 'default', 'value' => date('Y-d-m')],
            [['titulo'], 'string', 'max' => 255],
            [['categoria_id'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'titulo' => 'Titulo',
            'descripcion' => 'Descripcion',
            'contenido' => 'Contenido',
            'fecha' => 'Fecha',
            'imagen' => 'Imagen',
            'vistas' => 'Vistas',
            'usuario_id' => 'ID Usuario',
            'estado' => 'Estado',
            'categoria_id' => 'ID Categoria',
        ];
    }

    public function saveArticle()
    {
        $this->usuario_id = Yii::$app->user->id;
        return $this->save(false);
    }

    public function saveImage($filename)
    {
        $this->imagen = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->imagen) ? '/uploads/' . $this->imagen : '/no-image.png';
    }

    public function deleteImage()
    {
        $imagenUploadModel = new ImageUpload();
        $imagenUploadModel->deleteCurrentImage($this->imagen);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete();
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'categoria_id']);
    }

    public function saveCategory($categoria_id)
    {
        $category = Category::findOne($categoria_id);
        if($category != null)
        {
            $this->link('category', $category);
            return true;            
        }
    }

    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
            ->viaTable('articulos_tag', ['articulo_id' => 'id']);
    }
    
    public function getSelectedTags()
    {
         $selectedIds = $this->getTags()->select('id')->asArray()->all();
        return ArrayHelper::getColumn($selectedIds, 'id');
    }

    public function saveTags($tags)
    {
        if (is_array($tags))
        {
            $this->clearCurrentTags();

            foreach($tags as $tag_id)
            {
                $tag = Tag::findOne($tag_id);
                $this->link('tags', $tag);
            }
        }
    }

    public function clearCurrentTags()
    {
        ArticleTag::deleteAll(['articulo_id'=>$this->id]);
    }
    
    public function getDate()
    {
        return Yii::$app->formatter->asDate($this->fecha);
    }
    
    public static function getAll($pageSize = 5)
    {
        $query = Article::find();

        $count = $query->count();

        $paginacion = new Pagination(['totalCount' => $count, 'pageSize'=>$pageSize]);

        $articulos = $query->offset($paginacion->offset)
            ->limit($paginacion->limit)
            ->all();
        
        $data['articles'] = $articulos;
        $data['paginacion'] = $paginacion;
        
        return $data;
    }
    
    public static function getPopular()
    {
        return Article::find()->orderBy('vistas desc')->limit(3)->all();
    }
    
    public static function getRecent()
    {
        return Article::find()->orderBy('fecha asc')->limit(4)->all();
    }
    
    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['articulo_id'=>'id']);
    }

    public function getArticleComments()
    {
        return $this->getComments()->where(['estado'=>1])->all();
    }
    
    public function getAuthor()
    {
        return $this->hasOne(Usuarios::className(), ['id'=>'usuario_id']);
    }
    
    public function viewedCounter()
    {
        $this->vistas += 1;
        return $this->save(false);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Article;
use app\models\Category;
use app\models\CommentForm;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /* iNICIO */
    public function actionIndex()
    {
        $data = Article::getAll(5);
        $popular = Article::getPopular();
        $reciente = Article::getRecent();
        $categorias = Category::getAll();
        
        return $this->render('index',[
            'articles'=>$data['articles'],
            'paginacion'=>$data['paginacion'],
            'popular'=>$popular,
            'reciente'=>$reciente,
            'categorias'=>$categorias
        ]);
    }
    
    public function actionView($id)
    {
        $articulo = Article::findOne($id);
        $popular = Article::getPopular();
        $reciente = Article::getRecent();
        $categorias = Category::getAll();
        $comentarios = $articulo->getArticleComments();
        $comentariosForm = new CommentForm();

        $articulo->viewedCounter();
        
        return $this->render('single',[
            'articulo'=>$articulo,
            'popular'=>$popular,
            'reciente'=>$reciente,
            'categorias'=>$categorias,
            'comentarios'=>$comentarios,
            'comentariosForm'=>$comentariosForm
        ]);
    }
    
    public function actionCategory($id)
    {

        $data = Category::getArticlesByCategory($id);
        $popular = Article::getPopular();
        $reciente = Article::getRecent();
        $categorias = Category::getAll();
        
        return $this->render('category',[
            'articulos'=>$data['articulos'],
            'pagination'=>$data['pagination'],
            'popular'=>$popular,
            'reciente'=>$reciente,
            'categorias'=>$categorias
        ]);
    }

    public function actionComment($id)
    {
        $model = new CommentForm();
        
        if(Yii::$app->request->isPost)
        {
            $model->load(Yii::$app->request->post());
            if($model->saveComment($id))
            {
                Yii::$app->getSession()->setFlash('comment', 'Tu comentario se añadio correctamente!');
                return $this->redirect(['site/view','id'=>$id]);
            }
        }
    }

}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/category.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>
<!--main content start-->
<div class="main-content">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <?php

                foreach($articulos as $art):?>
                    <article class="post post-list">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="post-thumb">
                                <a href="<?= Url::toRoute(['site/view','id'=>$art->id]);?>"><img src="<?= $art->getImage();?>" alt="" class="pull-left"></a>

                                <a href="<?= Url::toRoute(['site/view','id'=>$art->id]);?>" class="post-thumb-overlay text-center">
                                    <div class="text-uppercase text-center">Ver Post</div>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="post-content">
                                <header class="entry-header text-uppercase">
                                    <h6><a href="<?= Url::toRoute(['site/category','id'=>$art->category->id]);?>"> <?= $art->category->titulo?></a></h6>

                                    <h1 class="entry-title"><a href="<?= Url::toRoute(['site/view','id'=>$art->id]);?>"></a></h1>
                                </header>
                                <div class="entry-content">
                                    <p><?= $art->descripcion?>
                                    </p>
                                </div>
                                <div class="social-share">
                                    <span class="social-share-title pull-left text-capitalize"> <?= $art->author->nombre;?> <?= $art->getDate();?></span>

                                </div>
                            </div>
                        </div>
                    </div>
                </article>
                <?php endforeach;?>

                <?php
                echo LinkPager::widget([
                    'pagination' => $pagination,
                ]);
                ?>
            </div>
            <?= $this->render('/partials/sidebar', [
                'popular'=>$popular,
                'reciente'=>$reciente,
                'categorias'=>$categorias
            ]);?>
        </div>
    </div>
</div>
<!-- end main content-->

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;
?>
<!--main content start-->
<div class="main-content">
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <?php foreach($articles as $art):?>
                    <article class="post">
                        <div class="post-thumb">
                            <a href="<?= Url::toRoute(['site/view', 'id'=>$art->id]);?>"><img src="<?= $art->getImage();?>" alt=""></a>

                            <a href="<?= Url::toRoute(['site/view', 'id'=>$art->id]);?>" class="post-thumb-overlay text-center">
                                <div class="text-uppercase text-center">Ver Post</div>
                            </a>
                        </div>
                        <div class="post-content">
                            <header class="entry-header text-center text-uppercase">
                                <h6><a href="<?= Url::toRoute(['site/category','id'=>$art->id])?>"> <?= $art->titulo; ?></a></h6>

                                <h1 class="entry-title"><a href="<?= Url::toRoute(['site/view', 'id'=>$art->id]);?>"><?= $art->titulo?></a></h1>


                            </header>
                            <div class="entry-content">
                                <p><?= $art->descripcion?>
                                </p>

                                <div class="btn-continue-reading text-center text-uppercase">
                                    <a href="<?= Url::toRoute(['site/view', 'id'=>$art->id]);?>" class="more-link">Continua Leyendo</a>
                                </div>
                            </div>
                            <div class="social-share">
                                <span class="social-share-title pull-left text-capitalize">En <?= $art->getDate();?></span>
                                <ul class="text-center pull-right">
                                    <li><a class="s-facebook" href="#"><i class="fa fa-eye"></i></a></li><?= (int) $art->vistas?>
                                </ul>
                            </div>
                        </div>
                    </article>
                <?php endforeach; ?>

                <?php
                    echo LinkPager::widget([
                        'pagination' => $paginacion,
                    ]);
                ?>
            </div>
            <?= $this->render('/partials/sidebar', [
                'popular'=>$popular,
                'reciente'=>$reciente,
                'categorias'=>$categorias
            ]);?>
        </div>
    </div>
</div>
<!-- end main content-->
<!--footer start-->

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Rellena los siguientes campos para iniciar sesión:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/single.php
<?php
use yii\helpers\Url;
?>
<!--main content start-->
<div class="main-content">
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <article class="post">
                    <div class="post-thumb">
                        <a href="blog.html"><img src="<?= $articulo->getImage();?>" alt=""></a>
                    </div>
                    <div class="post-content">
                        <header class="entry-header text-center text-uppercase">
                        <h6><a href="<?= Url::toRoute(['site/category','id'=>$articulo->id])?>"> <?= $articulo->titulo?></a></h6>

                            <h1 class="entry-title"><a href="<?= Url::toRoute(['site/view','id'=>$articulo->id])?>"><?= $articulo->titulo?></a></h1>


                        </header>
                        <div class="entry-content">
                            <?= $articulo->contenido?>
                        </div>

                        <div class="social-share">
							<span
                                class="social-share-title pull-left text-capitalize"> Publicado por: <?= $articulo->author->nombre?> en <?= $articulo->getDate();?></span>
                            <ul class="text-center pull-right">
                                <li><a class="s-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a class="s-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a class="s-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a class="s-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a class="s-instagram" href="#"><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </article>

             <?= $this->render('/partials/comment', [
                 'articulo'=>$articulo,
                 'comentarios'=>$comentarios,
                 'comentariosForm'=>$comentariosForm
             ])?>
            </div>
            <?= $this->render('/partials/sidebar', [
                'popular'=>$popular,
                'reciente'=>$reciente,
                'categorias'=>$categorias
            ]);?>
        </div>
    </div>
</div>
<!-- end main content-->